# Generated by Django 5.0.6 on 2024-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_pedido_carrinho_alter_pedido_user_delete_itempedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="bairro",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pedido",
            name="cep",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="pedido",
            name="cidade",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="pedido",
            name="complemento",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="numero",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="rua",
            field=models.CharField(default="", max_length=50),
        ),
    ]
