# Generated by Django 5.0.6 on 2024-07-03 14:44

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0003_pedido_bairro_pedido_cep_pedido_cidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="bairro",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[a-zá-ú\\s-]+", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cep",
            field=models.CharField(
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[0-9]{1,8}"), message="Digite apenas numeros"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cidade",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[a-zá-ú\\s-]+", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="complemento",
            field=models.CharField(
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[a-zá-ú\\s-]+", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero",
            field=models.CharField(
                default="",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[a-z0-9-]+", 2),
                        message="Não é aceito caracteres especias além do '-'",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="rua",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("[a-zá-ú\\s-]+", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
    ]
