# Generated by Django 5.0.6 on 2024-07-04 17:36

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_alter_pedido_bairro_alter_pedido_cep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="bairro",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-zá-ú\\s]{2,}$", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cep",
            field=models.CharField(
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[0-9]+$"), message="Digite apenas números"
                    ),
                    django.core.validators.MinLengthValidator(8),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cidade",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-zá-ú\\s]{2,}$", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="complemento",
            field=models.CharField(
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-zá-ú\\s]{2,}$", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero",
            field=models.CharField(
                default="",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z0-9]+$", 2),
                        message="Não é aceito caracteres especias",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="rua",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-zá-ú\\s]{2,}$", 2),
                        message="Não é aceito caracteres especiais nem números",
                    )
                ],
            ),
        ),
    ]
