# Generated by Django 5.0.6 on 2024-06-07 15:45

import django.core.validators
import re
import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_staff",
            new_name="is_admin",
        ),
        migrations.AddField(
            model_name="customuser",
            name="bairro",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cep",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cidade",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="complemento",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="estado",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="numero",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rua",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(
                max_length=14,
                null=True,
                unique=True,
                validators=[
                    usuarios.validators.eh_valido_cpf,
                    django.core.validators.RegexValidator(
                        re.compile("^[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}\\-[0-9]{2}$"),
                        "CPF não está no padrão exigido",
                        "invalid",
                    ),
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="data_nascimento",
            field=models.DateField(
                null=True, validators=[usuarios.validators.eh_de_maior]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z0-9._]+@[a-z]+\\.([a-z]{3,})(\\.[a-z]{2,})?$"),
                        "Endereço de email inválido",
                    )
                ],
                verbose_name="endereço de email",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nome_completo",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-zá-ú\\s]+$"),
                        "Caracteres inválidos, insira apenas letras",
                    )
                ],
                verbose_name="nome",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telefone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\(?[0-9]{2}\\)?[\\s]?[9]?[0-9]{4}[-]?[0-9]{4}$"),
                        "Número telefone inválido",
                    )
                ],
            ),
        ),
    ]
