# Generated by Django 5.0.6 on 2024-07-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_customuser_cpf_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bairro",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="complemento",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="rua",
        ),
    ]
