# Generated by Django 5.0.6 on 2024-06-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_ingrediente_marca_remove_itemcarrinho_carrinho_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="principal",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="descricao",
        ),
        migrations.AddField(
            model_name="categoria",
            name="descricao",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="categoria",
            name="imagem_categorias",
            field=models.ImageField(
                blank=True,
                help_text="Imagem que será exibida na página da categoria",
                null=True,
                upload_to="categoria_imagem_sub_categorias/%Y/%m",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="imagem_principal",
            field=models.ImageField(
                blank=True,
                help_text="Imagem que será exibida na home page",
                null=True,
                upload_to="categoria_imagem_principal/%Y/%m",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="SubCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(null=True, unique=True)),
                (
                    "destaque",
                    models.BooleanField(
                        default=False,
                        help_text="Destina a categoria que ficará em exibição na home page. obs: se mais de uma categoria for destinada para ser destaque, a categoria escolhida será feita por ordem alfabetica",
                    ),
                ),
                ("descricao", models.TextField(default="")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categorias",
                        to="produtos.categoria",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="produto",
            name="categorias",
            field=models.ManyToManyField(
                related_name="produtos", to="produtos.subcategoria"
            ),
        ),
    ]
